---
# tasks file for roles/apache-debian role
- name: Install Apache Server
  apt:
    name: apache2
    state: latest
    update_cache: yes

- name: install proxy related modules
  apt:
    name: build-essential
    state: latest
    update_cache: yes


- name: enable proxy related modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
  - proxy
  - proxy_ajp
  - proxy_http
  - rewrite
  - deflate
  - headers
  - proxy_balancer
  - proxy_connect
  - proxy_html

- name: Disable default virtualhost
  file: 
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: restart apache


- name: Create loadbalancer configuration
  template:
    src: templates/loadbalancer.j2
    dest: /etc/apache2/sites-available/loadbalancer.conf
    owner: root
    mode: '0644'
  notify: restart apache

- name: create a symlink to enable loadbalancer.conf
  file:
    src: /etc/apache2/sites-available/loadbalancer.conf
    dest: /etc/apache2/sites-enabled/loadbalancer.conf
    state: link
  notify: restart apache

- name: Start and enable apache services
  service:
    name: apache2
    state: started
    enabled: yes


- name: Configurar firewall
  ufw:
    rule: allow 
    port: "{{ item }}"
    state: enabled
  loop:
    - 80
    - 443
